using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Net.Json;
using System.Xml;
using System.IO;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace NDS20WinPlayer
{
    public partial class ManagerForm : DevExpress.XtraEditors.XtraForm
    {
        //public List<string> arSchedule;
        
        public ManagerForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            //JsonArrayCollection arrCol = new JsonArrayCollection();


            //treeList1.DataSource = new System.Collections.Generic.List<System.Net.Json.JsonArrayCollection>();

            //List<scheduleclass> shclist = new List<scheduleclass>();

            //shclist.Add(new scheduleclass
            //    {
            //        tlclScheduleField = "schedule1"
            //    });


            string jsonSchedule = "[" +
                "{'tlclScheduleField':'sc2', 'tlclTypeField':'기본','tlclStartDateField':'2015-07-28T12:00Z', 'tlclEndDateField':'2015-08-30T12:00:00Z'}," +
                "{'tlclScheduleField':'sc3', 'tlclTypeField':'기본', 'tlclStartDateField':'2015-07-28T12:00Z', 'tlclEndDateField':'2015-08-30T12:00:00Z'}," +
                "{'tlclScheduleField':'sc4', 'tlclTypeField':'이벤트', 'tlclStartDateField':'2015-07-28T12:00Z', 'tlclEndDateField':'2015-08-30T12:00:00Z'}" +
                "]";

            scheduleclass[] shclist = JsonConvert.DeserializeObject<scheduleclass[]>(jsonSchedule, new IsoDateTimeConverter());

            treeList1.DataSource = shclist;

            /*
            arSchedule.Add(
                "{" +
                " \"tlclSchedule\": \"A.avi\"," +
                " \"xPos\": 400," +
                " \"yPos\": 100," +
                " \"width\": 700," +
                " \"height\": 396," +
                " \"fileName\": \"D:/Projects/NDS/Contents/A.avi\"," +
                " \"mute\": true " +
                "}"
                );

            arSchedule.Add(
                "{" +
                " \"tlclSchedule\": \"A.avi\"," +
                " \"xPos\": 400," +
                " \"yPos\": 100," +
                " \"width\": 700," +
                " \"height\": 396," +
                " \"fileName\": \"D:/Projects/NDS/Contents/A.avi\"," +
                " \"mute\": true " +
                "}"
                );
             */
            
            //pLinqServerModeSource1.Source = (System.Collections.Generic.IEnumerable<System.Net.Json.JsonArrayCollection>)null /* TODO: Assign the real System.Collections.Generic.IEnumerable source here.*/;
// This line of code is generated by Data Source Configuration Wizard
//treeList1.DataSource = new System.Collections.Generic.List<System.Net.Json.JsonArrayCollection>();
        }

        private void panelControl1_Paint(object sender, PaintEventArgs e)
        {

        }

        private void spltcontCntlManager_Paint(object sender, PaintEventArgs e)
        {
            
        }

        private void ManagerForm_KeyDown(object sender, KeyEventArgs e)
        {
            switch (e.KeyCode)
            {
                case Keys.Escape:
                    Close();
                    break;

            }
        }

        private void AssignScheduleFileToTreeList()
        {
           List<clssScheduleFileList> dataSource = new List<clssScheduleFileList>();

            System.IO.DirectoryInfo di = new System.IO.DirectoryInfo(AppInfoStrc.DirOfSchedule);

            foreach (System.IO.FileInfo f in di.GetFiles())
            {
                clssScheduleFileList item = new clssScheduleFileList();
                item.ctscName = f.Name;
                dataSource.Add(item);
            }
            
            trlstSchedule.DataSource = dataSource;

        }

        private void AssignLogFileToTreeList()
        {
            List<clssLogFileList> dataSource = new List<clssLogFileList>();

            System.IO.DirectoryInfo di = new System.IO.DirectoryInfo(AppInfoStrc.DirOfLog);

            foreach (System.IO.FileInfo f in di.GetFiles())
            {
                clssLogFileList item = new clssLogFileList();
                item.logFileName = f.Name;
                dataSource.Add(item);
            }

            trlstLogFile.DataSource = dataSource;

        }

        private void loadLogFileAndConnectDataSource(string  prmLogFileName);
        {
            //string logFileFullPath = AppInfoStrc.DirOfLog + "\\" + prmLogFileName;

        }



        private void trlstSchedule_Load(object sender, EventArgs e)
        {
            AssignScheduleFileToTreeList();
        }

        private void trlstSchedule_FocusedNodeChanged(object sender, DevExpress.XtraTreeList.FocusedNodeChangedEventArgs e)
        {
            string schedulename = e.Node.GetDisplayText("ctscName");
            string scheduleFilePath = AppInfoStrc.DirOfSchedule + "\\" + schedulename;
            string scheduleText = System.IO.File.ReadAllText(@scheduleFilePath);

            //string scheduleTexo = "[{'scheCatagory':'일반','scheType':'기본','ctscKey':'스케줄키02','ctscName':'Schedule20150801.sch','ctscStartdate':'2015-08-01T12:00Z','ctscEnddate':'2015-08-30T12:00Z'}]";

            clssScheduleFileList[] shclist = JsonConvert.DeserializeObject<clssScheduleFileList[]>(scheduleText, new IsoDateTimeConverter());


            memoEdit1.Text = shclist[0].scheCatagory;

            //MessageBox.Show(scheduleFilePath);

        }

        private void trlstLogFile_FocusedNodeChanged(object sender, DevExpress.XtraTreeList.FocusedNodeChangedEventArgs e)
        {

        }

        private void trlstLogFile_Load(object sender, EventArgs e)
        {
            AssignLogFileToTreeList();
        }
    }

}